config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'events#index'
resources :events do
  resources :attendances
end
resources :users
resources :charges
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
class Attendance < ApplicationRecord
  after_create :attendance_confirm

  belongs_to :attendee, class_name: "User"
  belongs_to :event

  def attendance_confirm
    AttendanceMailer.event_attendance_confirmation(self).deliver_now
  end

end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :admin, class_name: "User"
  has_many :attendances
  has_many :attendees, class_name: "User", through: :attendances
  validates :start_date, presence: true 
  validate :not_in_the_past
  validates :duration, presence: true, numericality: { greater_than: 0, only_integer: true}
  validate :multiple_of_5
  validates :title, presence: true, length: {in: 5..140}
  validates :description, presence: true,  length: {in: 20..1000}
  validates :price, presence: true, numericality: {greater_than: 0, less_than_or_equal_to: 1000}
  validates :location, presence: true 

  private 

  def not_in_the_past
    errors.add(:start_date, "Can't be in the past") unless start_date.present? && start_date > Date.today    
  end

  def multiple_of_5
    errors.add(:duration, "Must be a multiple of 5") unless self.duration.to_i % 5 == 0
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  after_create :welcome_send
  
  has_many :attendances, foreign_key: 'attendee_id'
  has_many :events, foreign_key: 'admin_id'
  #validates :first_name, presence: true
  #validates :last_name, presence: true
  #validates :description, presence: true

  def welcome_send
    UserMailer.welcome_email(self).deliver_now
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?  
  
  protected  
  
  def configure_permitted_parameters
   devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])
  end
  
end

app/controllers/attendances_controller.rb
class AttendancesController < ApplicationController

  def new
    @event = Event.find(params[:event_id])
    @attendees = @event.attendees.count
  end

  def index
    @event = Event.find(params[:event_id])
    @attendees = @event.attendees
  end
  
  def create
    @event = Event.find(params[:event_id])
    @user = current_user

    @amount = @event.price * 100

    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Paiement évènement',
      :currency    => 'eur'
    )
    
    a = Attendance.create(event: @event, attendee: @user, stripe_customer_id: params[:stripeToken])
    
    if a.save 
      flash[:success] = "Votre participation à l'évènement a été enregistrée"
      redirect_to event_path @event
    else 
      flash[:danger] = "Connecte toi pour rejoindre un évènement"
      redirect_to event_path @event
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to @event

  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create
    # Amount in cents
    @events = Event.all
    @amount = 500 #@event.price
    @user = User.all
  
    customer = Stripe::Customer.create(
      :email => params[:stripeEmail],
      :source  => params[:stripeToken]
    )
  
    charge = Stripe::Charge.create(
      :customer    => customer.id,
      :amount      => @amount,
      :description => 'Paiement de #{@user.name}',
      :currency    => 'eur'
    )
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end

end

app/controllers/events_controller.rb
class EventsController < ApplicationController

  before_action :authenticate_user!, only: [:new ,:create, :destroy, :udpate]
  # before_action :event_admin, only:[:update, :destroy, :edit]

  def show
    @event=Event.find(params[:id])
    @attendees=@event.attendances
    @user=current_user
  end

  def index
    @events=Event.all
  end

  def new
    @event = Event.new
    @user_id = current_user.id
  end

  def create

    @title = params[:event][:title]
    @description = params[:event][:description]
    @location = params[:event][:location]  
    year = params[:user][:born_on][0,4].to_i
    month = params[:user][:born_on][5,2].to_i
    day = params[:user][:born_on][8,2].to_i
    hour = params[:task][:started_at][0,2].to_i
    minute = params[:task][:started_at][3,2].to_i
    seconde = 0
    @start_date = DateTime.new(year,month,day,hour,minute,seconde)
    @duration = params[:duration][:price].to_i
    @price = params[:price][:price].to_i
    @admin = current_user
   
    e=Event.create(start_date: @start_date, duration: @duration, title: @title, description: @description, price: @price, location: @location, admin: @admin)
    
    if e.save
     flash[:success] = "Ton évènement a bien été créé"
          redirect_to event_path(e)

    elsif 
     flash[:danger] = "Une erreur est survenue"
      redirect_to new_event_path
    end
  end

  def destroy
    @event = Event.find(params[:id])
    @event.destroy
    redirect_to root_path 
    flash[:success] = "Ton évènement a bien été supprimé"
  end


 def edit
  @event=Event.find(params[:id])
end


def update
 @event = Event.find(params[:id])
 title = params[:event][:title]
 description = params[:event][:description]
 location = params[:event][:location]
 duration = params[:event][:duration].to_i
 price = params[:event][:price].to_i
 start_date = params[:event][:start_date]
 admin = current_user
 @event.update(title:title, description:description,location:location, duration:duration, price:price, start_date:start_date, admin:admin)
 puts @event.errors.messages

  if @event.save
  flash[:success] = "Ton évènement a été modifié"
   redirect_to event_path(@event)

 else
  flash[:danger] = "Une erreur s'est produite"
   redirect_to edit_event_path(@event)
 end
end

  private 
=begin
  def event_admin
    if current_user != User.find(params[:id])
      flash[:danger] = "Tu ne peux pas accéder à cette page"
    end
  end
=end 

  def authenticate_user
    unless current_user
      flash[:danger] = "Tu dois être connecté pour accéder à ce contenu"
      redirect_to user_session_path
    end
  end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: [:show, :edit ]
	before_action :owner, only: [:show, :edit]

	def show
		@user=current_user
		@events=@user.events
	end

	def edit
		@user=current_user
	end

	def update
		@user=current_user
	
		puts first_name = params[:user][:first_name]
		puts last_name = params[:user][:last_name]
		puts description =  params[:user][:description]

		 @user.update(first_name: first_name, last_name: last_name,  description: description)
	


		if @user.save
			flash[:success] = "Tes changements ont été enregistrés"
			redirect_to user_path(@user)
		else
			flash[:danger] = "Une erreur est survenue"
			edit_user_path(@user)
		end

	end
  

private

	def owner
		 if current_user != User.find(params[:id])
  		 flash[:danger] = "Tu ne peux pas accéder aux autres profils"    
  		 redirect_to events_path
		end
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper

	def flash_class(level)
    case level
        when 'notice' then "alert alert-info"
        when 'success' then "alert alert-success"
        when 'danger' then "alert alert-danger"
        when 'warning' then "alert alert-warning"
    end
end

end

app/helpers/attendances_helper.rb
module AttendancesHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/attendances/index.html.erb
<div class="d-flex flex-column align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
<center>
<h1>Liste des participants</h1>
</br>
<%=link_to 'Modifier mon évènement', edit_event_path(@event), class:'btn btn-danger' %>
</br>
</center>
</br>


<table class="table d-flex flex-column align-items-center p-6 px-md-6 mb-6 bg-white border-bottom shadow-sm">
  <thead>
    <tr>
      <th scope="col">Prénom</th>
      <th scope="col">Nom</th>
      <th scope="col">Email</th>
    </tr>
  </thead>
  <tbody>
  <% @attendees.each do |a| %>
    <tr>
      <td><%=a.first_name%></td>
      <td><%=a.last_name%></td>
      <td><%=a.email%></td>
    </tr>
  <% end %>
  </tbody>

</table>
  <%= button_to  "Supprimer mon évènement", event_path(@event), type: 'submit', class: 'btn btn-warning', method: 'delete', data: { confirm: "Êtes-vous sûr(e)" } %>
</div>

app/views/attendances/new.html.erb
<div style="border: 1px solid #e3e3e3; margin-top: 20px; padding: 10px;"class="col-9 offset-2">
<h1> <%=@event.title%></h1>
<h3><%=@event.description%></h3>
<br>
<p>Date :<span style="color:#2b84ee" ><%=@event.start_date.year%>/<%=@event.start_date.month%>/<%=@event.start_date.day%> <span></p>
<p>Démarre à:  <span style="color:#2b84ee" ><%=@event.start_date.hour%>:<%=@event.start_date.min%></span></p>
<p>Durée : <span style="color:#2b84ee" > <%=@event.duration%> mins</span></p>
<br>
<p>Crée par :<span style="color:#2b84ee" > <%=@event.admin.first_name%></span> | Prix :<span style="color:#2b84ee" >  <%=@event.price%></span></p>
<p>Lieu : <span style="color:#2b84ee" ><%=@event.location%></span></p>
<p>Participants :<span style="color:#2b84ee" > <%=@attendees%></span></p>

<p>Pour rejoindre l'évènement, merci de régler votre participation de : <%= @event.price%>€</p>
<%= form_tag event_attendances_path(@event) do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Montant: <%= @event.price %> </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Paiement évènement"
          data-amount= <% @amount %>
          data-locale="auto"></script>
<% end %>

app/views/charges/create.html.erb
<h2>Merci votre paiement de <strong>$5.00</strong> a été pris en compte.</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Prix </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="Paiement pour l'évènement"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

app/views/events/_cardevent.html.erb
<div style="text-align:center"class="jumbotron">
  <h1 class="display-4">Les évènements à venir </h1>
  <p class="lead">Ne manque aucuns des évènements dans ta ville !</p>
  <hr class="my-4">     
   
  <p>Si tu as des propositions, c'est par là ↓↓↓</p>
  <p> <%= link_to "Créer un évènement", new_event_path, class:"btn btn-primary" %></p>
</div>

<div class="row">

	<%@events.each do |event|%>
	<div class="col-sm-4">            
	    <div class="card" style="margin-bottom:10px">
        <img src="https://picsum.photos/200/300/?random" class="card-img-top">
	      <div class="card-body">
	        <h5 class="card-title"><%=event.title%> </h5>

	        <p class="card-text"><%= event.description.first(80) %></p>
	        <p class="card-text">Date : <%=event.start_date%> |  Duration : <%=event.duration%></p>
          <p class="card-text"><small class="text-muted">Mis à jour le :<%=event.created_at%></small></p>
	 		<%= link_to "Détails", event_path(event), class:"btn btn-primary" %>
	    </div>
	  </div>	  
	 
	</div>
	<%end%>
</div>

app/views/events/_show.html.erb
<body>
  <div style="border: 2px solid #e3e3e3; margin-top: 20px; padding: 10px;"class="col-9 offset-2">
    <h1> <%=@event.title%></h1>
  </br></br>
  
  <div class="row">
      <div class="col-8"><img src="https://media.gettyimages.com/photos/clubbers-at-the-hacienda-in-manchester-for-a-popular-acid-house-night-picture-id595890347" alt="Acid Addict" width=90%></div>
      <div class="col-4">
        <p>Date :<span style="color:#2b84ee" ><%=@event.start_date.year%>/<%=@event.start_date.month%>/<%=@event.start_date.day%> <span></p>
        <p>Démarre à:  <span style="color:#2b84ee" ><%=@event.start_date.hour%>:<%=@event.start_date.min%></span></p>
        <p>Durée : <span style="color:#2b84ee" > <%=@event.duration%> mins</span></p>
        <br>
        <p>Crée par :<span style="color:#2b84ee" > <%=@event.admin.first_name%></span> | Prix :<span style="color:#2b84ee" >  <%=@event.price%></span></p>
        <p>Lieu : <span style="color:#2b84ee" ><%=@event.location%></span></p>
    </div>

    <div class="row mt-4">
      <div class="col-8">
            <h3><%=@event.description%></h3>
            </div>
        
        <div class="col-3">
            <div class="d-flex justify-content-end">
                <% if @event.admin == current_user %>
                <%= link_to  "Mon espace évènement", event_attendances_path(@event), class: "btn btn-info" %>
                <% elsif  @event.attendees.include? current_user %>
                <% else current_user != @event.admin %>
                <%= link_to "Rejoindre l'évènement", new_event_attendance_path(@event), class: "btn btn-primary" %>
                <% end %>
            </div>
          </div>

        <div class="col-2">
        <p>Nombre de participants :<span style="color:#2b84ee" > <%=@event.attendees.count%></span></p>
          </div>
        
    </div>
    </div>
</body>

app/views/events/create.html.erb
<h1>Event#create</h1>
<p>Find me in app/views/event/create.html.erb</p>

app/views/events/destroy.html.erb
<h1>Event#destroy</h1>
<p>Find me in app/views/event/destroy.html.erb</p>

app/views/events/edit.html.erb
<div class="col-6 offset-3">
	<br><br>
<h1>Modifer un évènement</h1>
<br><br>
		<%= form_for(:event, url: events_path, html: {method:'POST'} ) do |f| %>

			<div class="form-group">
			<label>Titre</label>
			<%= f.text_field :title , class:'form-control'%>
			</div>
		
			<div class="form-group">
			<label>Description</label>
			<%= f.text_field :description , class:'form-control'%>
			</div>

			<div class="form-group">
			<label>Date</label>
			<%= date_field(:user, :born_on) %> <%= time_field(:task, :started_at) %>
			</div>
			

			  <div class="form-group">
			<label>Durée</label>
			<%= number_field(:duration, :price, in: 5.0..500.0, step: 5) %>
			</div>

			 <div class="form-group">
			<label>Lieu</label>
			<%= f.text_field :location , class:'form-control'%>
			</div>
			

			<div class="form-group">
			<label>Prix</label>
			<%= number_field(:price, :price, in: 1.0..1000.0, step: 1) %>
			</div>

			<div class="form-group">
			<button type="submit" class="btn btn-primary" > Envoyer</button> 
			</div>

		<%end%>
</div>

app/views/events/index.html.erb
<%= render 'cardevent'%>

 

app/views/events/new.html.erb
<div class="col-6 offset-3">
	<br><br>
<h1>Créer un évènement</h1>
<br><br>
		<%= form_for(:event, url: events_path, html: {method:'POST'} ) do |f| %>

			<div class="form-group">
			<label>Titre</label>
			<%= f.text_field :title , class:'form-control'%>
			</div>
		
			<div class="form-group">
			<label>Description</label>
			<%= f.text_field :description , class:'form-control'%>
			</div>

			<div class="form-group">
			<label>Date</label>
			<%= date_field(:user, :born_on) %> <%= time_field(:task, :started_at) %>
			</div>
			

			  <div class="form-group">
			<label>Durée</label>
			<%= number_field(:duration, :price, in: 5.0..500.0, step: 5) %>
			</div>

			 <div class="form-group">
			<label>Lieu</label>
			<%= f.text_field :location , class:'form-control'%>
			</div>
			

			<div class="form-group">
			<label>Prix</label>
			<%= number_field(:price, :price, in: 1.0..1000.0, step: 1) %>
			</div>

			<div class="form-group">
			<button type="submit" class="btn btn-primary" > Envoyer</button> 
			</div>

		<%end%>
</div>

app/views/events/show.html.erb
<%= render  "show" %>

app/views/events/update.html.erb
<h1>Event#update</h1>
<p>Find me in app/views/event/update.html.erb</p>

app/views/layouts/_flash.html.erb
<% flash.each do |key, value| %>
      <div class="<%= flash_class(key) %>">
            <%= value %>
      </div>
<% end %>

app/views/layouts/_footer.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Footer</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Navbar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <link rel="stylesheet" href="style.css">
    <script src="main.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR|Permanent+Marker" rel="stylesheet"> 

    <!-- Bootstrap CSS -->
    
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"> 
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-kW2H6mf/72/MKlmwB//Zcwg0ckiegojPx/fio14/rpoYw2LMhULTn5YhS1QyrQfx" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <footer class="bg">
      <div class="container">
        <div class="row">
          <div class="col-sm md-6">
          </br>
            <p class="h2 text-white"><i class="far fa-star fa-xs mr-1"></i>Take Me Out</p><br>
            <p class="h4 text-white mt-1">Tu veux sortir ? On va t'aider !</p>
          </div>
          <div class="col-sm text-white">
  
          </div>
          <div class="col-sm">
          </br>
            <div class="copyright text-right text-white">
              <br><br>
              <p>© 2019 Take Me Out. Tous droits réservés.</p>
            </div>
          </div>
        </div>
      </div>
    </footer>
</html>

app/views/layouts/_header.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Navbar</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Navbar</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" type="text/css" media="screen" href="main.css">
    <link rel="stylesheet" href="style.css">
    <script src="main.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Noto+Sans+KR|Permanent+Marker" rel="stylesheet"> 

    <!-- Bootstrap CSS -->
   
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.3/css/all.css" integrity="sha384-UHRtZLI+pbxtHCWp1t77Bi1L4ZtiqrqD80Kn4Z8NTSRyMA2Fd33n5dQ8lWUE00s/" crossorigin="anonymous"> 
    <link href="https://stackpath.bootstrapcdn.com/bootswatch/4.2.1/lux/bootstrap.min.css" rel="stylesheet" integrity="sha384-kW2H6mf/72/MKlmwB//Zcwg0ckiegojPx/fio14/rpoYw2LMhULTn5YhS1QyrQfx" crossorigin="anonymous">

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </head>

  <header>

    <nav class="navbar sticky-top navbar-expand-lg navbar bg mb-0">
      <a class="navbar-brand" href="#">Take Me Out</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02"
        aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
  
      <div class="collapse navbar-collapse" id="navbarColor02">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item">
            <%= link_to "Accueil", root_path, class:"navbar-brand"%>
          </li>
          <li class="nav-item">
            <%= link_to "Tous les évènements", root_path, class:"navbar-brand"%>
          </li>
            <li class="nav-item">
            <%= link_to "Créér un évènement", new_event_path, class:"navbar-brand" %>          
            </li>
          </ul>
          <%if user_signed_in?%>

             <span class="right navbar-text">
             <%=current_user.first_name%>
             </span>
        
           <div style="padding-left:20px" class="btn-group btn-group-right">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               Mon Profil 
              </button>

              <div class="dropdown-menu">
              <%= link_to "Mon Profil ", user_path(current_user), class:"nav-link" %>
              <%= link_to "Éditer son Email / Mot de Passe", edit_user_registration_path, class:"nav-link" %>
              <%= link_to "Se Déconnecter", destroy_user_session_path, method: :delete, class:"nav-link" %>
              </div>
            </div>

          <%else%>
          <div style="padding-left:20px" class="btn-group btn-group-right">
              <button type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
               S'inscrire / Se Connecter
              </button>

              <div class="dropdown-menu">
                <%= link_to "Inscription", new_user_registration_path, class:"dropdown-item" %>
                <%= link_to "Se Connecter", new_user_session_path, class:"dropdown-item" %>
              </div>
            </div>           

            </div>
            <%end%><div style="padding-left:20px" class="btn-group btn-group-right">
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Rechercher">
            <button class="btn btn-secondary my-2 my-sm-0" type="submit">Rechercher</button>
          </form>
      </div>
    </nav>
  </header>
</html>
  

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<div class="d-flex flex-column align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
<div class="col-6 offset-3">
    <br><br>
<h1>Éditer mon profil</h1>
<br><br>
        <%= form_for(:user, url: user_path(@user), html: {method:'PATCH'} ) do |f| %>

            <div class="form-group">
            <label>Prénom</label></br>
            <%= text_field(:user, :first_name)%>
        	</div>
        
            <div class="form-group">
            <label>Nom</label></br>
            <%= text_field(:user, :last_name)%>
        	</div>


              <div class="form-group">
            <label>Description</label></br>
            <%= text_field(:user, :description)%>
            </div>



            <div class="form-group">
            <button type="submit" class="btn btn-primary" > Envoyer</button> 
            </div>

        <%end%>
</div>
</div>

app/views/users/show.html.erb
<div style="text-align:center"class="jumbotron">
  <h1 class="display-4"><%=@user.first_name%></h1>
  <p class="lead"><%=@user.description%></p>
  <hr class="my-4">     
   <p>Prénom :<%=@user.first_name%></p>
<p>Nom :<%=@user.last_name%></p>
<p>Email :<%=@user.email%></p>

<%=link_to "Éditer son profil", edit_user_path(@user), class:"btn btn-danger"%>

</div>



<div class="row">

	<%@events.each do |event|%>
	<div class="col-sm-4">
	    <div class="card" style="margin-bottom:10px">
	      <div class="card-body">
	        <h5 class="card-title"><%=event.title%> </h5>

	        <p class="card-text"><%= event.description.first(80) %></p>
	        <p class="card-text">Date : <%=event.start_date%> |  Duration : <%=event.duration%></p>
	 		
	 		<%=link_to "see event", event_path(event), class:"btn btn-primary"%>
	    </div>
	  </div>	  
	 
	</div>
	<%end%>
</div>